### ISSUE TITLE
get_occurrence in schedule/views.py is failing as occurrence is None 

### ISSUE THREAD

**Issue by sushovan23** [llazzaro/django-scheduler#289] opened 2017-01-24 16:26 UTC
Created one event 24 hrs duration with daily re-occurrence for a week. Then from daily calendar view and i'm clicking one any occurrence and clicking the option to edit 'This' occurrence from the popup dialog,

data in database:

```
+-----+---------------------+---------------------+-----------------+-------------+---------------------+---------------------+----------------------+-------------+------------+---------
| id  | start               | end                 | title           | description | created_on          | updated_on          | end_recurring_period | calendar_id | creator_id | rule_id
+-----+---------------------+---------------------+-----------------+-------------+---------------------+---------------------+----------------------+-------------+------------+---------
| 206 | 2017-01-13 15:00:00 | 2017-01-14 15:00:00 | smajum002c,test |             | 2017-01-24 14:22:02 | 2017-01-24 14:22:02 | 2017-01-20 05:00:00  |          11 |          1 |      10
```
Then it should go to edit occurrence page but it is failing since get_occurrence() is views.py has an issue in getting occurrence from method event.getoccurence() which returns None. Thus it doesn't go to edit occurrence page anymore.

**Comment by mpaolino** [comment] 2017-01-24 17:29
@sushovan23 I could reproduced it, but source of the problem seems to be different (at least on my tests). 
Offending code is actually https://github.com/llazzaro/django-scheduler/blob/develop/schedule/utils.py#L95-L108.

That method returns None and makes this fail:

https://github.com/llazzaro/django-scheduler/blob/develop/schedule/settings.py#L24

It will raise an AttributeError exception due to None not having an event.

The problem here is that the occurrence is not a persisted occurrence, hence there is no Occurrence object. Question is, should it be? @llazzaro can you shed some light?

**Comment by sushovan23** [comment] 2017-01-24 17:35
@mpaolino : you are correct. I first got that. Then I modified my app code to use previous implementation of editing occurrence which uses methods instead of class view. So I changed urls.py and used previous implementation which had method like `edit_occurrence` and that used to call `event, occurrence = get_occurrence(event_id, *args, **kwargs)`

This was old method:
```
@check_event_permissions
def edit_occurrence(request, event_id, template_name="schedule/edit_occurrence.html", *args, **kwargs):
    event, occurrence = get_occurrence(event_id, *args, **kwargs)
    next = kwargs.get('next', None)
    form = OccurrenceForm(data=request.POST or None, instance=occurrence)
    if form.is_valid():
        occurrence = form.save(commit=False)
        occurrence.event = event
        occurrence.save()
        next = next or get_next_url(request, occurrence.get_absolute_url())
        return HttpResponseRedirect(next)
    next = next or get_next_url(request, occurrence.get_absolute_url())
    return render_to_response(template_name, {
        'form': form,
        'occurrence': occurrence,
        'next': next,
    }, context_instance=RequestContext(request))
```
I wanted to get my previously working functionality of editing individual occurrences back so I checked with this older code.

**Comment by sushovan23** [comment] 2017-01-24 18:30
@mpaolino  You could try the way I mentioned for editing occurrence and it will go to get_occurrence from event object to get the non persisted occurrences from event object

**Comment by mpaolino** [comment] 2017-01-24 18:48
@sushovan23 the thing is I'm not sure what is the way to go here as I'm not familiar with the rationale behind the change that broke this. I'm a very recent contributor and my changes don't touch the views at all. We'll have to wait for the owner of the project to figure what to do here.

**Comment by sushovan23** [comment] 2017-01-24 19:18
@mpaolino : Ok  I understand.  I wanted to bring into your view the following:

https://github.com/llazzaro/django-scheduler/blob/develop/schedule/views.py#L249-L271

calls: event.get_occurrence from events.py
and that method was changed recently so I want to confirm it that event.get_occurrence would work the way it is called from here?

**Comment by mpaolino** [comment] 2017-01-24 19:59
@sushovan23 I see. 

At first glance the date kwargs are passed in local time (``America/NewYork`` in your case) but without a timezone, seems to me that the tzinfo parameter is always passed (incorrectly) as UTC and all other calls receive that. Hence the wrong occurrences or no occurrences at all are returned.

If you see other view the timezone is selected to be the current one currently active, like: https://github.com/llazzaro/django-scheduler/blob/develop/schedule/views.py#L102

Here you go, missing test: https://github.com/mpaolino/django-scheduler/blob/fix_view_get_occurrence/schedule/views.py#L259

Let me know if this fixes your issue.

**Comment by sushovan23** [comment] 2017-01-24 20:31
@mpaolino : Yes I fixed that in my code and I'm passing like below now:
```
date = timezone.make_aware(datetime.datetime(int(year), int(month), int(day), int(hour),
                              int(minute), int(second)), tzinfo)
occurrence = event.get_occurrence(date)
```
And in events.py 
I changed tzinfo = timezone.utc to tzinfo = timezone.get_current_timezone() and
```
if date.tzinfo:
            tzinfo = date.tzinfo
```
to 
```
if date.tzinfo:
            tzinfo = timezone.get_current_timezone()
```

After passing timezone like above I was able to edit single occurrence of event. I will do some more testing today

**Comment by mpaolino** [comment] 2017-01-24 20:56
Ok, great. I found another bug on get_occurrence :-/. If any of the datetime parameters is zero it will fail to return the event. I'll update my branch and eventually make a PR.

**Comment by sushovan23** [comment] 2017-01-24 21:04
@mpaolino  Thanks please mention it here so I can take it and test it out

**Comment by mpaolino** [comment] 2017-01-24 21:33
@sushovan23 #290

**Comment by mpaolino** [comment] 2017-01-24 21:37
Please notice that this branch has unmerged changes related to #286

**Comment by sushovan23** [comment] 2017-01-24 21:43
Got it.. Took changes in views.py. Rest I had. Thanks

**Comment by llazzaro** [comment] 2017-01-26 03:32
I will merge the pull request soon. @mpaolino you are great!

**Comment by llazzaro** [comment] 2017-06-25 19:28
Closing this issue. seems that the merge solved this bug

**Closed by llazzaro** 2017-06-25 19:28 UTC
