### ISSUE TITLE
Recurring events and DST 

### ISSUE THREAD

**Issue by lggwettmann** [llazzaro/django-scheduler#304] opened 2017-04-01 19:51 UTC
Hey guys,

In my Django settings, I have L10N active and the timezone set to "Europe/Paris". 

When a recurring event has been set before DST started, the event time is shown accurately before the DST started. When DST has started, the event time changes to be one hour later. I know this might have something to do with timezone aware date times, but there must be an easy fix for that besides running my whole Django setup timezone naive. I'd prefer not to do that, as the project will span multiple time zones later.

Did I set up the server faulty or how do you tackle this issue? 

Thanks in advance.

**Comment by mikekeda** [comment] 2017-06-11 08:24
Had a similar case with multiple time zones (time zone per user). I'm using an api, so I created PR to add timezone param to api_occurrences() #326.

Not sure if it will useful for your case.

**Comment by lggwettmann** [comment] 2017-06-13 01:44
Thanks, I'll definitely look into that :)

**Comment by as3445** [comment] 2017-09-26 20:02
This post seems helpful for this issue: https://serverfault.com/questions/549737/scheduled-jobs-during-hours-of-autumn-time-change

**Comment by Lucianovici** [comment] 2017-11-01 20:49
I found a particular solution for this kind of issue:

- set event in summer (DST), but have recurrent occurrences in winter (no DST)
- set event in winter (no DST), but have recurrent occurrences in summer (DST)

I use [DRF](http://www.django-rest-framework.org/) so I have a serializer for Occurrence model.

I just apply an offset to the occurrence start/end, depending on the event start/end DST offsets, so that there won't be any issues with recurring occurrences throughout the year.

Do you think this would be useful to add in django-schedule core, when computing the recurrent occurrences? Assuming we store the UTC datetime in database.

```
class OccurrenceSerializer(serializers.HyperlinkedModelSerializer):
    start = serializers.SerializerMethodField(method_name='get_start_dst_adjusted')
    end = serializers.SerializerMethodField(method_name='get_end_dst_adjusted')

    class Meta:
        model = schedule_models.Occurrence
        fields = ('id', 'title', 'description', 'start', 'end')

    def get_start_dst_adjusted(self, obj):
        event_start_dst_offset = timezone.localtime(obj.event.start).dst()
        occurrence_start_dst_offset = timezone.localtime(obj.start).dst()

        offset = event_start_dst_offset - occurrence_start_dst_offset

        return obj.start + offset

    def get_end_dst_adjusted(self, obj):
        event_end_dst_offset = timezone.localtime(obj.event.end).dst()
        occurrence_end_dst_offset = timezone.localtime(obj.end).dst()

        offset = event_end_dst_offset - occurrence_end_dst_offset

        return obj.end + offset
```

**Comment by lggwettmann** [comment] 2017-12-02 23:05
I'll try this in the coming month. Any chance of rewriting this so it not dependent on DRF?

**Comment by Lucianovici** [comment] 2017-12-03 11:37
I was wrong actually. django-scheduler is working fine _only_ if you provide the correct timezone for `Period` instances. Use the `tzinfo` kwarg.

Here is the method responsible for getting all occurrences.

```
from dateutil.parser import parse
from schedule.periods import Period
from django.utils import timezone


def get_localized_datetime_from_str(date_str):
    local_timezone = timezone.get_current_timezone()
    date = parse(date_str, ignoretz=True)
    date = local_timezone.localize(date)

    return date


class EventService(object):

    def get_occurrences_for_events(self, events, start_date_str, end_date_str):
        start_date = get_localized_datetime_from_str(start_date_str)
        end_date = get_localized_datetime_from_str(end_date_str)

        period = Period(events, start_date, end_date, tzinfo=start_date.tzinfo)

        return period.get_occurrences()
```

Before struggling with the DST issue the Period instance had the `tzinfo` missing.

**Comment by jdufresne** [comment] 2018-01-07 18:58
I believe this is a duplicate of #109

**Closed by jdufresne** 2018-01-07 18:58 UTC
