### ISSUE TITLE
Rest API

### ISSUE THREAD

**Issue by sophianachiba** [llazzaro/django-scheduler#197] opened 2016-04-29 03:13 UTC
Hi guys,

any chance this can work with django rest api?
are there serializer for the models?

thanks!

**Comment by llazzaro** [comment] 2016-05-29 00:36
I reopened this issue to add django rest framework

**Comment by joed4no** [comment] 2016-07-13 08:12
I am also looking at using this for a rest api... is there an update on this?

**Comment by llazzaro** [comment] 2016-08-18 03:00
@sophianachiba @joed4no  could you add more info about what you need? for example urls to create calendars, events, etc? that will help a lot.
I will create a wiki page to write about which urls we need.

**Comment by rohanthacker** [comment] 2016-09-21 23:20
@llazzaro Hey, Great work with this app! 
I'm looking to do the same as @joed4no and @sophianachiba. I would be glad to help you understand the requirements you have

**Comment by amitasthana** [comment] 2017-11-29 09:13
Hey what is the update to this?  

Can someone suggest something similar to Django-Scheduler which I can use with Django Rest Framework?

**Comment by jdufresne** [comment] 2018-01-07 18:44
Duplicate of #192

**Closed by jdufresne** 2018-01-07 18:44 UTC
Labels: enhancement
