### ISSUE TITLE
Problems working out how to display my calendar

### ISSUE THREAD

**Issue by ataktwo** [llazzaro/django-scheduler#348] opened 2017-09-22 19:56 UTC
Hello,

I'm having some problems getting django-scheduler to do what I need to do. I have had a look at django-scheduler-sample and I'm not sure how to manipulate it for my purposes.

I'm new to django and I am looking to display a calendar on the homepage I am making.

By my understanding of it, a calendar can be called using the scheduletags.

So I am trying to display a monthly calendar on my homepage. The calendar (created through the admin interface) is called "moovement".

So my html has this basic layout:

------------------------------------------------------------------

{% load scheduletags %}
{% load i18n %}
  
<html>
<body>
<script type="text/javascript" src="{% static "jquery/dist/jquery.js" %}"></script>
<script type="text/javascript" src="{% static "jquery-ui/jquery-ui.min.js" %}"></script>
<script type="text/javascript" src="{% static "bootstrap/dist/js/bootstrap.js" %}"></script>
<script type="text/javascript" src="{% static "schedule.js" %}"></script>
          
{% month_table moovement month 'small' %}
</body>
</html>

The problem is the calendar displays the days of the week but does not have the grid and dates that should be inside the tbody section. See screenshot below:

[image](https://imgur.com/GbgWqL0)

And this is the view I would like to see on my homepage:

[image](https://imgur.com/qGkmiYV)

Can you give me an idea on where I'm going wrong? If not, could you please give an example of how you would implement a monthly view of a calendar called "moovement" within a webpage.

Second problem:

I am also aware that there is a fullcalendar in the sample project. I am unable to use that as I get an error when I try to navigate to it's sample page:

[image](https://imgur.com/pME7vaX)

Why is this error coming up?

Thanks for taking the time to look at my issues.

**Comment by sinanthottan** [comment] 2017-12-29 17:38
Hello @ataktwo 
I was wondering where did you get this tag from?
{% month_table moovement month 'small' %}

Was looking for a tutorial on how to display the calendar and never found any good article. Can you please help me out.

Thanks

**Comment by ataktwo** [comment] 2017-12-30 00:47
Frankly @sinanthottan I am a beginner with Django and everything I have done is trial and error so I'm not sure how much help I can be to you.

The template tags that information came from is [http://django-scheduler.readthedocs.io/en/latest/template_tags.html](url)

If you look in your site-packages within your python library you will find the templatetag options within scheduletags.py. Mine was found at /YOURUSER/.local/lib/python2.7/site-packages/schedule/templatetags

I hope that information helps. As a beginner I never got the scheduler to work and moved on to another Django calendar app found here: [https://github.com/wreckage/django-happenings](url)

This was much easier for me to figure out as an absolute beginner. If you want help with happenings pm me and I will send you my websites html so you can see how that apps scheduletags have been implemented.

**Comment by jdufresne** [comment] 2018-01-07 18:03
I believe this is a duplicate of #97 which suggests to write a tutorial for  basic use.

**Closed by jdufresne** 2018-01-07 18:03 UTC
