### ISSUE TITLE
Can't figure out how to install

### ISSUE THREAD

**Issue by killerbarney** [llazzaro/django-scheduler#358] opened 2017-10-23 21:57 UTC
Maybe my Django game is weak, but I have no idea how to get this thing going. I followed the instructions and nothing shows up.

So then I tried the sample project, and then everything is out of whack there. As far as I can tell, none of the jQuery or bootstrap installed properly and who knows where the template files are, because I sure can't find them.

**Comment by sinanthottan** [comment] 2017-12-26 19:46
Hi @llazzaro 
Sorry to trouble you, i am new to django. Could not figure out how to display the calendar. 
Installation completed, but i have no clue on how to use the code on view.py and display my calendar
Your support is much appreciated.

Thank you

**Comment by jdufresne** [comment] 2018-01-04 03:43
Hi, thanks for reporting this issue. This looks like a duplicate of #167, which will be resolved by writing a tutorial for django-scheduler. If you have additional feedback to add on the subject, that issue would be a good sport to do so. Thanks.

**Closed by jdufresne** 2018-01-04 03:43 UTC
